#!/bin/bash
######################################################################
# 45eeepc-sound v1.3 By Adam McDaniel, (c) 2008
#
# System script that automatically configures the alsa snd_hda_intel 
# module and forces alsa suspending/resuming, depending on the Asus 
# Eee PC model.
#
# This script will only work on Asus equipment.
#
# The EeePC 900 uses the RealTek 269 sound chipset, however an issue 
# with this the snd_hda_intel Alsa module results in muted sound output 
# when resuming from a suspend.
# 
# The workaround to this is to force alsa to suspend and resume along 
# with the computer, which in turns unloads/loads the snd_hda_intel 
# module.
#
# One problem with this workaround is that applications which use the 
# sound card across the suspend/resume process (i.e., 
# gnome-volume-control applet) fail to return when the system comes up. 
# A warning/error message is presented to the user. This problem will 
# be fixed with a future version of Alsa.
#
# Adam McDaniel
# 2008-08-02
#
######################################################################

ALSA='/sbin/alsa'


# Sanity check

if [ ! -x "${ALSA}" ]; then
	exit 0;
fi


# Load shared functions

. /usr/lib/eeepc-config/functions


# Load defaults

if [ -e /etc/default/eeepc-config ]; then
    . /etc/default/eeepc-config
fi


# Is this a NetBook PC?

if ! isNetBook; then
	exit 0;
fi


# Only continue if we're using the EeePC 900

if ! isModelEqualTo "900"; then
    exit 0;
fi


######################################################################
#
# functions
#
######################################################################

set_eeepc900_quirk () {
	DEST="/etc/default/alsa"

	# Only modify ${DEST} if "force_unload_modules_before_suspend" is
	# either not found, or is blank.

	if grep -q "^force_unload_modules_before_suspend=" ${DEST}; then
		if grep -q "^force_unload_modules_before_suspend=\"\"$" ${DEST}; then
			# Delete the original config line. It will be corrected below.

			sed 's/^force_unload_modules_before_suspend=\"\"$//' < ${DEST} > ${DEST}.tmp
			mv ${DEST}.tmp ${DEST}
			chown root:root ${DEST}
		else
			# If the config line is found, or it is not *exactly* blank,
			# stop. Don't modify it because the user, or this script, have
			# already customized it.

			return 1
		fi
	fi

	# Apply the corrected line

	echo "# Modified by eeepc-config and /usr/lib/pm-utils/sleep.d/45eeepc-sleep" >> ${DEST}
	echo "# to force snd_hda_intel to unload when suspending. Sound fails to" >> ${DEST}
	echo "# resume on some devices without this setting." >> ${DEST}
	echo "force_unload_modules_before_suspend=\"snd_hda_intel\"" >> ${DEST}

	return 0
}

case "$1" in
	hibernate|suspend)
		set_eeepc900_quirk
		${ALSA} suspend
		;;
	thaw|resume)
		${ALSA} resume
		;;
	*)
		;;
esac

exit $?
