#!/bin/bash

######################################################################
# Main
######################################################################

DMIDEC='/usr/sbin/dmidecode'

VENDOR=`${DMIDEC} -s system-manufacturer`
PRODUCT=`${DMIDEC} -s system-product-name`



######################################################################
# Functions
######################################################################

isNetbook ()
{
	return 0;
}

isProduct ()
{
	if [ `echo "${PRODUCT}" | grep -qi $1 | wc -l` -eq 0 ]; then
		return 0
	fi

	return 1
}

isModelLessThan ()
{
	if [ "${PRODUCT}" \< "$1" ]; then
		return 0;
	fi

	return 1;
}


isModelLessThanOrEqualTo ()
{
	if [ "${PRODUCT}" \< "$1" -o "${PRODUCT}" = "$1" ]; then
		return 0;
	fi

	return 1;
}


isModelGreaterThan ()
{
	if [ "${PRODUCT}" \> "$1" ]; then
		return 0;
	fi

	return 1;
}


isModelGreaterThanOrEqualTo ()
{
	if [ "${PRODUCT}" \> "$1" -o "${PRODUCT}" = "$1" ]; then
		return 0;
	fi

	return 1;
}


isModelEqualTo ()
{
	if [ "${PRODUCT}" = "$1" ]; then
		return 1;
	fi

	return 0;
}


# vim:syntax=sh:noexpandtab
