#!/bin/bash

######################################################################
# Main
######################################################################

DMIDEC='/usr/sbin/dmidecode'

VENDOR=`${DMIDEC} -s system-manufacturer`
PRODUCT=`${DMIDEC} -s system-product-name`


######################################################################
# Functions
######################################################################

isNetbook ()
{
	return 0;
}

isProduct ()
{
	if [ `echo "${PRODUCT}" | grep -qi $1 | wc -l` -eq 0 ]; then
		return 0
	fi

	return 1
}

isModelLessThan ()
{
	return `expr "${PRODUCT}" "<" "$1"`;
}

isModelLessThanOrEqualTo ()
{
	return `expr "${PRODUCT}" "<=" "$1"`;
}

isModelGreaterThan ()
{
	return `expr "${PRODUCT}" ">" "$1"`;
}

isModelGreaterThanOrEqualTo ()
{
	return `expr "${PRODUCT}" ">=" "$1"`;
}

isModelEqualTo ()
{
	return `expr "${PRODUCT}" "=" "$1"`;
}


# vim:syntax=sh:noexpandtab
