#!/bin/bash

######################################################################
# Main
######################################################################

DMIDEC='/usr/sbin/dmidecode'
KERNEL=`uname -r`

VENDOR=`${DMIDEC} -s system-manufacturer`
PRODNM=`${DMIDEC} -s system-product-name`
SERIAL=`${DMIDEC} -s system-serial-number`
BIOS=`${DMIDEC} -s bios-version`


######################################################################
# Functions
######################################################################

isNetBook ()
{
	if echo "${VENDOR}" | grep -qi "asustek"; then
		#isSerial "eeepc"
		#if [ $? -eq 1 ]; then
		#	return 1;
		#fi

		return 0;
	fi

	if echo "${VENDOR}" | grep -qi "hewlett-packard"; then
		if isProduct "Tx1000"; then
			return 0;
		fi

		isProduct "Tx1100"
		if isProduct "Tx1100"; then
			return 0;
		fi
	fi

	return 1;
}

isNetBookKernel ()
{
	if isKernelNetBook; then
		return 0;
	fi

	return 1;
}

isProduct ()
{
	if echo "${PRODNM}" | grep -qi $1; then
		return 0;
	fi

	return 1;
}

isSerial ()
{
	if echo "${SERIAL}" | grep -qi $1; then
		return 0;
	fi

	return 1;
}

isModelLessThan ()
{
	perl -e "exit ( '${PRODNM}' <=> '$1' || lc '${PRODNM}' cmp lc '$1' )"
	# Perl returns 255 if $1 is less than ${PRODNUM}
	if [ $? -eq 255 ]; then
		return 0
	fi
	return 1
}

isModelLessThanOrEqualTo ()
{
	perl -e "exit ( '${PRODNM}' <=> '$1' || lc '${PRODNM}' cmp lc '$1' )"
	# Perl returns 255 if $1 is less than ${PRODNUM}, 0 if both values are
	# the same.
	if [ $? -eq 255 -o $? -eq 0 ]; then
		return 0
	fi
	return 1
}

isModelGreaterThan ()
{
	perl -e "exit ( '${PRODNM}' <=> '$1' || lc '${PRODNM}' cmp lc '$1' )"
	# Perl returns 1 if $1 is greater than $PRODNM
	if [ $? -eq 1 ]; then
		return 0
	fi
	return 1
}

isModelGreaterThanOrEqualTo ()
{
	perl -e "exit ( '${PRODNM}' <=> '$1' || lc '${PRODNM}' cmp lc '$1' )"
	# Perl returns 1 if $1 is greater than $PRODNM, 0 if both values are
	# the same.
	if [ $? -eq 1 -o $? -eq 0 ]; then
		return 0
	fi
	return 1
}

isModelEqualTo ()
{
	perl -e "exit ( '${PRODNM}' <=> '$1' || lc '${PRODNM}' cmp lc '$1' )"
	# Perl returns 0 if $1 and $PRODNM are the same.
	if [ $? -eq 0 ]; then
		return 0
	fi
	return 1
}

isKernelNetBook ()
{
	if isKernelEeePC; then
		return 0;
	fi
	if isKernelEeePCAtom; then
		return 0;
	fi

	return 1;
}

isKernelEeePC ()
{
	if echo "${KERNEL}" | grep -q eeepc$; then
		return 0;
	fi

	return 1;
}

isKernelEeePCAtom ()
{
	return 1;
}

isKernelEarlierThan ()
{
	expr "${KERNEL}" "<" "$1" > /dev/null
	return $?
}

isKernelEarlierThanOrEqualTo ()
{
	expr "${KERNEL}" "<=" "$1" > /dev/null
	return $?
}

isKernelLaterThan ()
{
	expr "${KERNEL}" ">" "$1" > /dev/null
	return $?
}

isKernelLaterThanOrEqualTo ()
{
	expr "${KERNEL}" ">=" "$1" > /dev/null
	return $?
}

isKernelEqualTo ()
{
	expr "${KERNEL}" "=" "$1" > /dev/null
	return $?
}


# vim:syntax=sh:noexpandtab
