#!/bin/sh
######################################################################
# eeepc-config by F.Hendrikx, (c) 2008
# jolicloud-netbook-config by Adam McDaniel, (c) 2009
# postinst script
######################################################################
# This script can be called in the following ways:
#
# After the package was installed:
#       <postinst> configure <old-version>
#
# If prerm fails during upgrade or fails on failed upgrade:
#       <old-postinst> abort-upgrade <new-version>
#
# If prerm fails during deconfiguration of a package:
#       <postinst> abort-deconfigure in-favour <new-package> <version>
#                  removing <old-package> <version>
#
# If prerm fails during replacement due to conflict:
#       <postinst> abort-remove in-favour <new-package> <version>

set -e

case "$1" in
    configure)

        # remove asus mail ACPI event, causes conflict with some hotkeys
        rm -f /etc/acpi/events/asus-mail

        # restart ACPI
        invoke-rc.d acpid restart

        # Change grub default timeout
        if [ -w /boot/grub/menu.lst ] ; then
            sed -i.dpkg-old -e 's/^timeout[ \t]*[0-9]*$/timeout\t\t1/' /boot/grub/menu.lst
        fi

        if dpkg --compare-versions "$2" le "2:2.0.0"; then
            dpkg-divert --add --package "jolicloud-netbook-config" --divert /usr/lib/jolicloud-netbook-config/ondemand-diverted.init --rename /etc/init.d/ondemand
        fi

        ;;

    abort-upgrade|abort-deconfigure|abort-remove)
        ;;

    *)
        echo "$0 called with unknown argument \`$1\'" 1>&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
