#!/bin/sh
######################################################################
# eeepc-config by F.Hendrikx, (c) 2008
# jolicloud-netbook-config by Adam McDaniel, (c) 2009
# postrm script
######################################################################
set -e

case "$1" in
    remove|pruge)
        dpkg-divert --rename --remove /etc/init.d/ondemand
    ;;
esac

#DEBHELPER#

exit 0
