#!/bin/sh
######################################################################
# eeepc-config by F.Hendrikx, (c) 2008
# jolicloud-netbook-config by Adam McDaniel, (c) 2009
# postrm script
######################################################################
set -e


# remove jolicloud-netbook-config init.d script

update-rc.d -f jolicloud-netbook-config remove >/dev/null || exit $?

exit 0
