#!/bin/sh
######################################################################
# eeepc-config by F.Hendrikx, (c) 2008
# jolicloud-netbook-config by Adam McDaniel, (c) 2009
# postinst script
######################################################################
set -e


# add eeepc-config init.d script

if [ -x "/etc/init.d/jolicloud-netbook-config" ]; then
	update-rc.d jolicloud-netbook-config start 40 2 3 4 5 . stop 85 0 . || exit $?
fi


# remove asus mail ACPI event, causes conflict with some hotkeys

rm -f /etc/acpi/events/asus-mail


# restart ACPI

invoke-rc.d acpid restart


# start eeepc-config

invoke-rc.d jolicloud-netbook-config start


exit 0
