#!/bin/sh
######################################################################
# eeepc-config by F.Hendrikx, (c) 2008
# jolicloud-netbook-config by Adam McDaniel, (c) 2009
# postinst script
######################################################################
set -e


# remove asus mail ACPI event, causes conflict with some hotkeys

rm -f /etc/acpi/events/asus-mail


# restart ACPI

invoke-rc.d acpid restart


# start jolicloud-netbook-config

start jolicloud-netbook-config


# Change grub default timeout

if [ -w /boot/grub/menu.lst ] ; then
    sed -i.dpkg-old -e 's/^timeout[ \t]*[0-9]*$/timeout\t\t1/' /boot/grub/menu.lst
fi


# Re-enable init script 'ondemand', we no longer handle it ourselves.
# Earlier versions of JNC disabled this script. Keeping this "chmod +x"
# code is only required for the first JNC upgrade, or after the PreBeta is
# released.

if [ ! -x /etc/init.d/ondemand ]; then
    chmod +x /etc/init.d/ondemand;
fi


#DEBHELPER#

exit 0
